@echo off
chcp 936 >nul
rem ============================================
rem  Rebuild FDE one-click launcher exe
rem  Usage: edit scripts\start-fde.cs then double-click this file
rem  Requires: .NET Framework 4.x (built into Windows)
rem  Icon: static\img\favicon.ico (generated by generate-logo-assets.ps1)
rem ============================================
setlocal
set "CSC=%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not exist "%CSC%" set "CSC=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if not exist "%CSC%" (
    echo [错误] 未找到 C# 编译器 csc.exe，请确认已安装 .NET Framework 4.x
    pause
    exit /b 1
)
set "ROOT=%~dp0.."
set "ICON=%ROOT%\static\img\favicon.ico"
if not exist "%ICON%" (
    echo [提示] 未找到图标文件，将生成无图标版本。可运行 scripts\generate-logo-assets.ps1 生成。
    set "ICONARG="
) else (
    set "ICONARG=/win32icon:"%ICON%""
)
echo 正在编译 FDE一键启动.exe ...
"%CSC%" /nologo /target:exe /codepage:65001 %ICONARG% /out:"%ROOT%\FDE一键启动.exe" "%~dp0start-fde.cs"
if errorlevel 1 (
    echo [错误] 编译失败。若提示文件被占用，请先关闭正在运行的启动器窗口再重试。
    pause
    exit /b 1
)
echo [成功] 已重新生成 FDE一键启动.exe
pause
